apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
  name: db
spec:
  ndb:
    clusterId: "6096b588-3299-466d-8d1d-cb7e386de4f5"
    credentialSecret : ntnx1-ndb-secret
    server: https://erard4wm0y57c-era.nutanixtestdrive.com/era/v0.9
    skipCertificateVerification: true
  databaseInstance:
    databaseInstanceName: "testdb"
    databaseNames:
      - database_one
      - database_two
      - database_three
    credentialSecret: ntnx1-db-secret
    size: 10
    timezone: "UTC"
    type: postgres

