apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
  name: db12
spec:
  ndb:
    clusterId: "a52a3561-bbb7-415c-94af-0f8ed886f3e4"
    credentialSecret: ntnx1-ndb-secret
    server: https://eradcljh2n9li-era.nutanixtestdrive.com/era/v0.9
    skipCertificateVerification: true
  databaseInstance:
    databaseInstanceName: "db12"
    databaseNames:
      - database_one
      - database_two
      - database_three
    credentialSecret: ntnx1-db-secret
    size: 10
    timezone: "UTC"
    type: postgres

