apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
  name: db5
spec:
  ndb:
    clusterId: "64598461-9ab5-4fbe-b8ca-63ca98645645"
    credentialSecret : ntnx1-ndb-secret
    server: https://erajc79mswrn2-era.nutanixtestdrive.com/era/v0.9
    skipCertificateVerification: true
  databaseInstance:
    databaseInstanceName: "db5"
    databaseNames:
      - database_one
      - database_two
      - database_three
    credentialSecret: ntnx1-db-secret
    size: 200
    timezone: "UTC"
    type: mongodb
